services:
  android-build:
    build:
      context: .
      dockerfile: Dockerfile.android
    volumes:
      # Pasta onde o APK ser√° salvo
      - ./output:/app/output
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - ANDROID_SDK_ROOT=/opt/android-sdk
